
spring:
  profiles:
    active: ${ENV:dev}

  mail:
    host: smtp.gmail.com
    port: 587
    username: maheshwad123@gmail.com
    password: timp oyli nybo zvme
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
            
 

  
